AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'gemfiles/**/*'

Layout/AccessModifierIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/active_remote-cached.rb'


Metrics/ModuleLength:
  Exclude:
    - 'lib/active_remote/cached.rb' # this module is big

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/HashSyntax:
  Description: >-
                 Prefer Ruby 1.8 hash syntax { :a => 1, :b => 2 }
                 over 1.9 syntax { a: 1, b: 2 }.
  StyleGuide: 'https://git.moneydesktop.com/dev/ruby-style-guide#hash-literals'
  EnforcedStyle: hash_rockets
  Exclude:
    - 'Gemfile'

# Use lambdas instead of stabbys
Style/Lambda:
  EnforcedStyle: lambda

Style/MissingRespondToMissing:
  Enabled: false
